fix errors on Safari
[Error] Missing initialization of polymer elements. Please check that the list of entry points in your pubspec.yaml is correct. If you are using pub-serve, you may need to restart it.
	X1 (main.dart.precompiled.js, line 26424)
	Ok (main.dart.precompiled.js, line 26416)
	(anonymous function) (main.dart.precompiled.js, line 25449)
	(anonymous function) (main.dart.precompiled.js, line 892)
	RqO (main.dart.precompiled.js, line 676)
	(anonymous function) (main.dart.precompiled.js, line 32474)
	(anonymous function) (main.dart.precompiled.js, line 32474)
	onLoad (main.dart.precompiled.js, line 32473)
[Error] TypeError: 'undefined' is not an object (evaluating 'fYK.prototype.grZK=function(receiver){return receiver.alt}') (main.dart.precompiled.js, line 32664)
[Error] NoSuchMethodError : method not found: 'Symbol("main")' (index.html_bootstrap.dart.precompiled.js, line 1424)
Receiver: ""
Arguments: []